--- #YAML:1.0
name:               CGI-Application-Plugin-AuthRunmode
version:            0.01
abstract:           interrupt runmode by login transparently
author:
    - WATANABE Hiroaki <hwat@mac.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:  {}
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
